L1 = [1, 8,7,2,21,15]
#Sorting ( Sort the list ascending order)
L1.sort()
print(L1)
#Reverse (reverse the list)
L1.reverse()
print(L1)
# Appending ( Add something in the end of the list)
L1.append(11)
print(L1)
#Inserting ( add values to the particular index)
L1.insert(5, 55)
print(L1) 
#Pop ( it pops(delete) the value at given index)
L1.pop(0)
print(L1)
# REmove(Remove the given value )
L1.remove(15)
print(L1)
